name: Package Detailed Textures for Cold Ice Remastered

on: [push]

env:
  FOLDER_NAME: .
  CHECKOUT: actions/checkout@v4
  UPLOAD: actions/upload-artifact@v4

jobs:
  package_detailed_textures:
    runs-on: windows-latest

    steps:
    - uses: ${{env.CHECKOUT}}

    - name: Write Config File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        "`$Config = @{ 'projectName' = 'Cold Ice Remastered' }" | Add-Content .\${{env.FOLDER_NAME}}\Config.ps1

    - name: Package Detail Textures Pack
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{env.FOLDER_NAME}}\Build-Textures-Pack.ps1 -ConfigFile Config

    - name: Archive Detail Textures Pack Release
      uses: ${{env.UPLOAD}}
      with:
        name: detailed-textures-pack
        path: ${{env.FOLDER_NAME}}\detailed-textures-pack-git-*.7z
        if-no-files-found: error
